---
abstract: 'image processing library (using the Leptonica library)'
author:
  - 'Zakariyya Mughal <zmughal@cpan.org>'
build_requires:
  Alien::Leptonica: 0
  DDP: 0
  Inline: 0
  Path::Class: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Image-Leptonica
recommends:
  PDL: 0
requires:
  Alien::Leptonica: 0
  Inline: 0
  XSLoader: 0
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/zmughal/p5-Image-Leptonica
  repository: https://github.com/zmughal/p5-Image-Leptonica.git
version: 0.001
