#!/usr/bin/env perl

use strict;
use warnings;

use FindBin qw($Bin);
use Path::Class;
use JSON::MaybeXS;

my $json_f = dir($Bin)->parent->file('doc.json');

my $all_headers_f = dir($Bin)
	->subdir( qw(.. .. leptonica-1.70 src))
	->file('allheaders.h');
my $leptonica_h_f = dir($Bin)
	->subdir( qw(.. .build latest lib Image Leptonica))
	->file('leptonica.h');

my $json_data = decode_json( $json_f->slurp );

# TODO
#
# [_] Find all functions that are in allheaders.h.
# [_] Find all functions in leptonica.h
# [_] Mark the difference as NOT IMPLEMENTED
# [_] LATER: mark some functions as "TODO document" (make a list) because some
#     are not documented properly [_] only make docs for functions in leptonica.h
# [_] group the functions by their filename, sorted by name
